### ISSUE TITLE
Revit converters are in a 'revit' sub-folder

### ISSUE THREAD

**Issue by wynged** [ParallaxTeam/HyparElementConverters#14]
Thanks for making an installer!  One little issue.

https://github.com/ParallaxTeam/HyparElementConverters/blob/58467782c46a3ff9bc31b0ece11258050560d1d5/installer/HyparRevitCurtainWallConverter.iss#L6

The Revit converters are actually in a Revit subfolder inside this converters folder.

![image](https://user-images.githubusercontent.com/5872187/103574587-366f5f80-4e9e-11eb-9331-df444e7546b3.png)

**Comment by johnpierson** [comment]
daaaaaaaangit. fixing now.
