### ISSUE TITLE
ToHypar - Handling Mullions

### ISSUE THREAD

**Issue by johnpierson** [ParallaxTeam/HyparElementConverters#3]
Mullions seem to be accessible here, https://github.com/hypar-io/Schemas/blob/master/Mullion.json

but I am not too sure if they are wrapped in the Elements library here yet, https://github.com/hypar-io/Elements

any advice @wynged?

**Comment by wynged** [comment]
The elements library is designed to be extendable, so more and more you'll see classes/types on the Hypar platform that don't exist inside the Elements library.  Elements will be the necessary core to support all other types, but the goal is to have the various types represented outside of the Elements library.  So for example we want Elements to contain geometry methods, but we'd actually like to move things like Floors out of the core library.
