### ISSUE TITLE
ToHypar - Curtain Wall Class

### ISSUE THREAD

**Issue by johnpierson** [ParallaxTeam/HyparElementConverters#4]
Where to access CurtainWallPanel class for Hypar Elements? 

cc @wynged

**Comment by wynged** [comment]
Great question.  Here is a URL to the schema so you can see what you're working with. 
https://prod-api.hypar.io/schemas/CurtainWallPanel

Let's setup a call to chat about how you might be able to modify / add schemas in the future.
